[project]
name = "md2image"
version = "0.1.0"
description = ""
authors = [
    {name = "shaun",email = "beingswu@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "openai (>=2.14.0,<3.0.0)",
    "pillow (>=12.1.0,<13.0.0)"
]

[tool.poetry]
package-mode = false
packages = [{include = "md2image", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
